Repository BinaryStudioAcademy/bsa-2019-fantasy, pull requests merged in 2019-08, with the labels that each got.

#1 Feature/auth pages
  client/package.json
  client/postcss.config.js
  client/src/assets/images/login-bg.jpg
  client/src/components/AuthForms/LoginForm.jsx
  client/src/components/AuthForms/RegistrationForm.jsx
  client/src/components/AuthForms/styles.scss
  client/src/containers/Auth/Login/LoginPage.jsx
  client/src/containers/Auth/Login/responsive.scss
  client/src/containers/Auth/Registration/RegistartionPage.jsx
  client/src/containers/Auth/Registration/responsive.scss
  client/src/containers/Auth/styles.scss
  client/src/containers/Routing/index.jsx
  client/src/index.css
  client/src/index.jsx
  client/src/styles/tailwind.css
  client/tailwind.js
Labels: enhancement

#2 Migrate front-end part to Typescript
  .gitignore
  client/jsconfig.json
  client/package.json
  client/src/containers/PrivateRoute/index.jsx
  client/src/containers/PrivateRoute/index.tsx
  client/src/containers/Profile/action.type.ts
  client/src/containers/Profile/actionTypes.js
  client/src/containers/Profile/actions.js
  client/src/containers/Profile/actions.ts
  client/src/containers/Profile/index.jsx
  client/src/containers/Profile/index.tsx
  client/src/containers/Profile/profileActionTypes.js
  client/src/containers/Profile/reducer.js
  client/src/containers/Profile/reducer.ts
  client/src/containers/Routing/index.jsx
  client/src/containers/Routing/index.tsx
  client/src/containers/Test/action.type.ts
  client/src/containers/Test/actionTypes.js
  client/src/containers/Test/actions.js
  client/src/containers/Test/actions.ts
  client/src/containers/Test/index.tsx
  client/src/containers/Test/reducer.js
  client/src/containers/Test/reducer.ts
  client/src/helpers/webApiHelper.ts
  client/src/index.jsx
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/src/scenes/Home/index.tsx
  client/src/scenes/NotFound/index.tsx
  client/src/services/authService.ts
  client/src/services/testService.ts
  client/src/store/index.ts
  client/src/store/types.ts
  client/src/types/auth.types.ts
  client/src/types/user.type.ts
  client/tsconfig.json
Labels: enhancement

#3 Feature/Page 404
  client/src/scenes/NotFound/index.tsx
  client/src/scenes/NotFound/styles.scss
Labels: enhancement

#5 Add ESLint + Prettier to front-end part
  .gitignore
  client/.eslintrc
  client/.eslintrc.js
  client/.prettierrc.js
  client/.vscode/extensions.json
  client/.vscode/settings.json
  client/package.json
Labels: enhancement

#7 Feature/auth-logic. Implement local and facebook authorization
  server/.env.example
  server/api/middlewares/fb-auth-redirect.middleware.js
  server/api/middlewares/fb-auth.middleware.js
  server/api/routes/auth.routes.js
  server/api/routes/index.js
  server/api/services/auth.service.js
  server/api/services/user.service.js
  server/config/passport.config.js
  server/config/routes-white-list.config.js
  server/helpers/crypto.helper.js
  server/package.json
  server/server.js
Labels: enhancement

#11 Feature/integ-models-seeds
  server/data/db/associations.js
  server/data/db/connection.js
  server/data/migrations/20190608072702-create-tables.js
  server/data/migrations/20190608072802-add-associations.js
  server/data/migrations/20190805190224-create-test.js
  server/data/migrations/20190806082318-create-user.js
  server/data/models/event.js
  server/data/models/football-club.js
  server/data/models/game.js
  server/data/models/gameweek-history.js
  server/data/models/gameweek.js
  server/data/models/index.js
  server/data/models/league-participant.js
  server/data/models/league.js
  server/data/models/player-match-stat.js
  server/data/models/player-stat.js
  server/data/models/season.js
  server/data/models/test.js
  server/data/models/user.js
  server/data/seed-data/csv/football_clubs.csv
  server/data/seed-data/csv/player_stats.csv
  server/data/seed-data/events.seed.js
  server/data/seed-data/football-clubs.seed.js
  server/data/seed-data/games.seed.js
  server/data/seed-data/gameweek-histories.seed.js
  server/data/seed-data/gameweeks.seed.js
  server/data/seed-data/league-participants.seed.js
  server/data/seed-data/leagues.seed.js
  server/data/seed-data/player-match-stats.seed.js
  server/data/seed-data/player-stats.seed.js
  server/data/seed-data/seasons.seed.js
  server/data/seed-data/test.seed.js
  server/data/seed-data/users.seed.js
  server/data/seeders/20190805193335-test.js
  server/data/seeders/20190807073132-fill-db.js
  server/package.json
Labels: enhancement

#10 Feature/Leagues Layout
  client/package.json
  client/src/assets/images/1966.png
  client/src/assets/images/player.png
  client/src/components/Leagues/CreateLeague/index.tsx
  client/src/components/Leagues/JoinLeague/PrivateLeagues.tsx
  client/src/components/Leagues/JoinLeague/PublicLeagues.tsx
  client/src/components/Leagues/JoinLeague/index.tsx
  client/src/components/Leagues/JoinLeague/styles.scss
  client/src/components/Leagues/LeagueTables/index.tsx
  client/src/components/Leagues/LeagueTables/styles.scss
  client/src/containers/Leagues/index.tsx
  client/src/containers/Leagues/styles.scss
  client/src/containers/Routing/index.tsx
Labels: enhancement

#13 fix prettier eslint integration
  client/.vscode/settings.json
Labels: bug

#16 add spinner component
  client/src/components/Spinner/index.tsx
  client/src/components/Spinner/styles.scss
  client/src/containers/Routing/index.tsx
Labels: enhancement

#23 Fix mistakes in event model
  client/src/generated/tailwind.output.css
  server/data/migrations/20190608072702-create-tables.js
  server/data/models/football-club.js
  server/data/seed-data/events.seed.js
Labels: bug

#26 Feature/forgot password
  client/src/components/AuthForms/LoginForm.tsx
  client/src/components/ChangePasswordForms/ForgotPasswordForm.tsx
  client/src/components/ChangePasswordForms/ResetPasswordForm.tsx
  client/src/containers/ChangePassword/ForgotPassword.tsx
  client/src/containers/ChangePassword/ResetPassword.tsx
  client/src/containers/Profile/actions.ts
  client/src/containers/Routing/index.tsx
  client/src/services/authService.ts
  client/src/services/forgotPasswordService.ts
  client/src/types/auth.types.ts
  client/src/types/forgot.password.types.ts
  server/api/routes/auth.routes.js
  server/api/routes/forgot.password.routes.js
  server/api/routes/index.js
  server/api/services/password.service.js
  server/api/services/user.service.js
  server/package.json
Labels: enhancement

#33 Feature/Gameweek-team-route
  server/api/routes/gameweek-history.routes.js
  server/api/services/gameweek-history.service.js
  server/api/services/player.service.js
Labels: enhancement

#34 Add ESLint Prettier to server
  .gitignore
  server/.eslintrc
  server/.prettierrc
  server/.vscode/extensions.json
  server/.vscode/settings.json
  server/jsconfig.json
  server/package.json
Labels: enhancement

#36 Fix/reset password profile page
  client/src/containers/Profile/components/PersonalDetails/index.tsx
  client/src/containers/Profile/components/PersonalDetails/styles.module.scss
  client/src/containers/Profile/components/SetPassword/index.tsx
  client/src/containers/Profile/components/SetPassword/styles.scss
  client/src/containers/Routing/index.tsx
Labels: enhancement

#41 Fix/main routing
  client/src/components/Fixtures/Fixtures.tsx
  client/src/components/Header/index.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/Sidebar/styles.module.scss
  client/src/components/Sidebar/styles.scss
  client/src/containers/Fixtures/action.type.ts
  client/src/containers/Fixtures/actions.ts
  client/src/containers/Fixtures/index.tsx
  client/src/containers/Fixtures/reducer.ts
  client/src/containers/Fixtures/styles.module.scss
  client/src/containers/MyTeam/action.type.ts
  client/src/containers/MyTeam/actions.ts
  client/src/containers/MyTeam/index.tsx
  client/src/containers/MyTeam/reducer.ts
  client/src/containers/Routing/index.tsx
  client/src/containers/Transfers/action.type.ts
  client/src/containers/Transfers/actions.ts
  client/src/containers/Transfers/index.tsx
  client/src/containers/Transfers/reducer.ts
  client/src/scenes/NotFound/styles.scss
Labels: enhancement

#46 Fix/user gameweek team route
  server/api/routes/gameweek-history.routes.js
  server/api/routes/user.routes.js
  server/api/services/gameweek-history.service.js
  server/api/services/team-member-history.service.js
  server/data/repositories/gameweek-history.repository.js
  server/data/repositories/team-member-history.repository.js
Labels: bug, enhancement

#51 add team-selection component to the corresponding routes
  client/package.json
  client/src/components/Gameweek/PlayerSelection/index.tsx
  client/src/components/Gameweek/PlayerSelection/types.ts
  client/src/components/Gameweek/PlayerSelectionDroppable/index.tsx
  client/src/components/Gameweek/PlayerSelectionDroppable/styles.scss
  client/src/components/Gameweek/TeamSelection/index.tsx
  client/src/containers/GameweekHistory/index.tsx
  client/src/containers/MyTeam/index.tsx
  client/src/containers/MyTeam/styles.scss
Labels: enhancement

#53 fix warnings during compilation
  client/src/components/Fixtures/Fixtures.tsx
  client/src/components/Gameweek/TeamSelection/index.tsx
  client/src/containers/FixturesContainer/index.tsx
  client/src/containers/Players/actions.ts
  client/src/containers/Profile/index.tsx
  client/src/store/index.ts
Labels: bug

#58 drag and drop within pitch and bench
  client/src/components/Gameweek/PlayerSelection/index.tsx
  client/src/components/Gameweek/PlayerSelectionDroppable/index.tsx
  client/src/components/Gameweek/TeamSelection/index.tsx
Labels: enhancement

#60 get rid of the search field in the header
  client/src/components/Header/index.tsx
Labels: bug

#62 Feature/my team
  client/src/components/Gameweek/TeamSelection/index.tsx
Labels: enhancement

#63 Feature/my team
  client/src/components/Gameweek/TeamSelection/index.tsx
Labels: enhancement

#64 Feature/my team
  client/src/components/Gameweek/TeamSelection/index.tsx
Labels: enhancement

#65 gameweek chart implementation
  client/src/containers/GameweekHistory/index.tsx
  client/src/containers/GameweekHistory/styles.scss
Labels: enhancement

#72 fix gameweek-history team route
  server/api/routes/gameweek-history.routes.js
  server/api/routes/user.routes.js
Labels: bug

#75 fix pitch view behavior on the main page
  client/src/components/Gameweek/PlayerSelection/index.tsx
  client/src/components/Gameweek/PlayerSelectionDroppable/index.tsx
  client/src/components/Gameweek/TeamSelection/index.tsx
Labels: bug

#77 Fix/gameweek history route
  server/api/routes/gameweek-history.routes.js
  server/api/services/team-member-history.service.js
Labels: bug

#95 transfer drag and drop behavior implamentation
  client/src/components/Gameweek/PlayerSelection/types.ts
  client/src/components/Gameweek/PlayerSelectionDroppable/index.tsx
  client/src/components/Gameweek/TeamSelection/index.tsx
  client/src/components/PlayerItem/index.tsx
  client/src/components/PlayersList/index.tsx
  client/tsconfig.json
Labels: enhancement

#98 fix resetting password
  client/src/components/ChangePasswordForms/ForgotPasswordForm.tsx
  client/src/components/ChangePasswordForms/ResetPasswordForm.tsx
  client/src/containers/Routing/index.tsx
  server/api/services/user.service.js
  server/data/repositories/user.repository.js
Labels: bug

#102 fix adding user to global leagues due to db changes
  server/api/services/league.service.js
Labels: bug

#104 Feature/joining leagues
  client/package.json
  client/src/containers/Leagues/CreateLeague/index.tsx
  client/src/containers/Leagues/JoinLeague/PrivateLeagues.tsx
  client/src/containers/Leagues/JoinLeague/PublicLeagues.tsx
  client/src/containers/Leagues/JoinLeague/styles.scss
  client/src/containers/Leagues/action.types.ts
  client/src/containers/Leagues/actions.ts
  client/src/containers/Leagues/index.tsx
  client/src/containers/Leagues/reducer.ts
  client/src/containers/Leagues/styles.scss
  client/src/services/leagueService.ts
  client/src/types/league.types.ts
  server/api/middlewares/league.middleware.js
  server/api/routes/league.routes.js
  server/api/routes/user.routes.js
  server/api/services/league-participant.service.js
  server/api/services/league.service.js
  server/data/db/associations.js
  server/data/repositories/gameweek.repository.js
  server/data/repositories/league-participant.repository.js
  server/data/repositories/league.repository.js
Labels: enhancement

#108 implement selected team saving and restoring
  client/src/components/Gameweek/PlayerSelection/types.ts
  client/src/components/Gameweek/TeamSelection/index.tsx
  client/src/containers/GameweekHistory/index.tsx
  client/src/containers/MyTeam/index.tsx
  client/src/containers/Profile/components/PersonalDetails/index.tsx
  client/src/containers/Routing/fetchGameweeks/action.type.ts
  client/src/containers/Routing/fetchGameweeks/actions.ts
  client/src/containers/Routing/fetchGameweeks/reducer.ts
  client/src/containers/Routing/index.tsx
  client/src/containers/Transfers/index.tsx
  client/src/helpers/webApiHelper.ts
  client/src/services/gameweekHistoryService.ts
  client/src/types/gameweek.type.ts
  client/src/types/gameweekHistory.type.ts
  server/.vscode/extensions.json
  server/.vscode/settings.json
  server/api/routes/gameweek-history.routes.js
  server/api/services/gameweek-history.service.js
  server/api/services/league-participant.service.js
  server/api/services/team-member-history.service.js
  server/data/db/associations.js
  server/data/models/gameweek-history.js
  server/data/repositories/gameweek-history.repository.js
  server/data/repositories/team-member-history.repository.js
  server/data/seed-data/gameweek-histories.seed.js
  server/server.js
  server/socket/teamScoreRecalculator.js
Labels: enhancement

#112 replace mocked data into helpers
  client/src/components/Gameweek/TeamSelection/index.tsx
  client/src/containers/GameweekHistory/index.tsx
  client/src/helpers/dragndrop.ts
  client/src/helpers/gameweekChart.ts
Labels: bug

#113 remove commented code
  client/src/containers/GameweekHistory/index.tsx
Labels: bug

#115 Feature/gameweek statistic
  server/api/routes/gameweek-history.routes.js
  server/api/services/gameweek-history.service.js
  server/api/services/team-member-history.service.js
  server/data/repositories/gameweek-history.repository.js
  server/data/repositories/player.repository.js
  server/data/repositories/team-member-history.repository.js
Labels: enhancement

#117 fix D&D between bench players
  client/src/components/Gameweek/TeamSelection/index.tsx
Labels: bug

#128 fix leagues layout
  client/src/containers/Leagues/index.tsx
  client/src/containers/Leagues/styles.module.scss
Labels: enhancement

#133 Feature/gameweek statistic/ implement user ranking in overall league
  client/src/containers/GameweekHistory/index.tsx
  client/src/containers/Routing/fetchGameweeks/action.type.ts
  client/src/containers/Routing/fetchGameweeks/actions.ts
  client/src/containers/Routing/fetchGameweeks/reducer.ts
  client/src/containers/Routing/index.tsx
  client/src/services/gameweekHistoryService.ts
  client/src/types/gameweekHistory.type.ts
  server/api/routes/gameweek-history.routes.js
  server/api/services/gameweek-history.service.js
  server/api/services/user.service.js
  server/data/repositories/gameweek-history.repository.js
  server/data/repositories/user.repository.js
Labels: enhancement

#142 fix merge conflict
  client/src/containers/Leagues/reducer.ts
Labels: bug

#144 Feature/email preferences
  client/package.json
  client/src/containers/Profile/action.type.ts
  client/src/containers/Profile/actions.ts
  client/src/containers/Profile/components/EmailPreferences/index.tsx
  client/src/containers/Profile/reducer.ts
  client/src/i18n/locales/en.json
  client/src/i18n/locales/ua.json
  client/src/services/profileService.ts
  client/src/types/user.type.ts
  server/api/routes/profile.routes.js
  server/api/routes/season.routes.js
  server/data/migrations/20190608072702-create-tables.js
  server/data/models/user.js
  server/schedulers/team-reminder.scheduler.js
Labels: enhancement

#145 Fix/unificate icons
  client/package.json
  client/src/components/Dropdown/index.tsx
  client/src/components/Header/index.tsx
  client/src/components/Header/styles.module.scss
  client/src/components/Notifications/index.tsx
  client/src/components/Notifications/styles.module.scss
  client/src/components/PlayerHighlight/index.tsx
  client/src/components/SearchBar/index.tsx
  client/src/components/Sidebar/index.tsx
Labels: enhancement

#147 Fix/favoutite club selection layout
  client/src/components/AuthForms/LoginForm.tsx
  client/src/components/AuthForms/RegistrationForm.tsx
  client/src/components/ChangePasswordForms/ForgotPasswordForm.tsx
  client/src/components/ChangePasswordForms/ResetPasswordForm.tsx
  client/src/containers/Auth/Login/LoginPage.tsx
  client/src/containers/Auth/Registration/RegistrationPage.tsx
  client/src/containers/Auth/styles.module.scss
  client/src/containers/ChangePassword/ForgotPassword.tsx
  client/src/containers/ChangePassword/ResetPassword.tsx
  client/src/containers/Routing/index.tsx
Labels: enhancement

#151 Fix/auth buttons
  client/src/components/AuthForms/LoginForm.tsx
  client/src/components/AuthForms/RegistrationForm.tsx
  client/src/containers/Auth/styles.module.scss
Labels: bug

#156 add localization to status page
  client/src/components/Gameweek/TeamSelection/index.tsx
  client/src/containers/FixturesContainer/index.tsx
  client/src/containers/GameweekHistory/index.tsx
  client/src/containers/Profile/components/PersonalDetails/index.tsx
  client/src/helpers/gameweekChart.ts
  client/src/i18n/locales/en.json
  client/src/i18n/locales/ua.json
Labels: enhancement

#157 Feature/fixtures subscriptions to receive notifications on email
  client/src/components/Fixtures/FixturesItem.tsx
  client/src/containers/Profile/actions.ts
  client/src/i18n/locales/en.json
  client/src/i18n/locales/ua.json
  client/src/services/profileService.ts
  server/api/routes/profile.routes.js
  server/api/services/fixtures-subscription.service.js
  server/data/migrations/20190608072702-create-tables.js
  server/data/migrations/20190608072802-add-associations.js
  server/data/models/fixtures-subscription.js
  server/data/models/index.js
  server/data/repositories/fixtures-subscription.repository.js
  server/data/repositories/game.repository.js
  server/helpers/send-fixture-details.helper.js
  server/schedulers/fixtures-reminder.sceduler.js
  server/schedulers/index.js
Labels: enhancement

#158 Fix/network requests errors
  server/api/routes/gameweek-history.routes.js
  server/api/services/gameweek-history.service.js
  server/api/services/team-member-history.service.js
  server/schedulers/fixtures-reminder.sceduler.js
Labels: bug

#160 Fix/league details route
  client/src/containers/Leagues/LeagueDetails/index.tsx
  server/api/middlewares/league.middleware.js
  server/api/routes/league.routes.js
Labels: enhancement

#161 Feature/fixtures subscription
  client/src/components/Fixtures/Fixtures.tsx
  client/src/components/Fixtures/FixturesItem.tsx
  client/src/containers/FixturesContainer/action.type.ts
  client/src/containers/FixturesContainer/actions.ts
  client/src/containers/FixturesContainer/index.tsx
  client/src/containers/FixturesContainer/reducer.ts
  client/src/containers/Profile/actions.ts
  client/src/containers/Routing/index.tsx
  client/src/helpers/handlers.ts
  client/src/helpers/socket.ts
  client/src/services/profileService.ts
  client/src/types/fixture.types.ts
  client/src/types/fixtures.types.ts
  server/api/routes/profile.routes.js
  server/api/services/fixtures-subscription.service.js
  server/data/repositories/fixtures-subscription.repository.js
  server/helpers/fixture-notification.helper.js
  server/socket/handlers.js
Labels: enhancement

#162 add email notifications with game results
  server/helpers/fixture-notification.helper.js
  server/helpers/send-fixture-details.helper.js
  server/schedulers/fixtures-reminder.sceduler.js
Labels: enhancement

#163 remove extra username field
  client/src/containers/Profile/components/PersonalDetails/index.tsx
Labels: bug

#164 add ability to subscribe to notifications of the past fixtures
  client/src/components/Fixtures/FixturesItem.tsx
  server/helpers/send-fixture-details.helper.js
Labels: enhancement

#170 centered login form
  client/src/components/AuthForms/LoginForm.tsx
Labels: bug

#172 Fix/fixture subscribtions
  client/src/components/Fixtures/FixturesItem.tsx
  client/src/containers/FixturesContainer/actions.ts
Labels: bug

#176 create SMTP pool
  server/helpers/send-email.helper.js
  server/helpers/send-fixture-details.helper.js
Labels: bug

#177 Fix/gsmptp
  server/helpers/email-template.helper.js
  server/helpers/send-email.helper.js
  server/helpers/send-fixture-details.helper.js
  server/schedulers/fixtures-reminder.sceduler.js
  server/schedulers/team-reminder.scheduler.js
Labels: bug, enhancement

#178 render player statistics for all matches during gameweek
  client/src/components/PlayerDialog/index.tsx
  server/api/services/player-match.service.js
  server/helpers/send-email.helper.js
Labels: bug
