Repository BinaryStudioAcademy/bsa-2019-fantasy, pull requests merged in 2019-09, with the labels that each got.

#182 Fix/render all gw results modal
  client/src/containers/PlayersComparison/index.tsx
  server/api/services/player-match.service.js
Labels: bug

#183 Feature/display next fixture for players on my-team tab
  client/src/components/Pitch/components/PitchPlayer/index.tsx
  client/src/components/Pitch/components/PitchPlayer/styles.ts
  client/src/components/Pitch/helpers.ts
  client/src/components/Pitch/index.tsx
  client/src/components/Pitch/types.ts
  client/src/components/Pitch/use-pitch-players.hook.ts
  client/src/components/TeamSelection/index.tsx
  client/src/containers/MyTeam/index.tsx
  client/src/containers/Routing/fetchGameweeks/actions.ts
  client/src/containers/SquadSelection/index.tsx
  client/src/containers/Transfers/index.tsx
  client/src/services/playersService.ts
  client/src/types/fixture.types.ts
  client/src/types/gameweekHistory.type.ts
  server/api/routes/player-match.routes.js
  server/api/services/player-match.service.js
  server/data/repositories/player.repository.js
  server/socket/teamScoreRecalculator.js
Labels: enhancement

#186 Fix/subscribe button position
  client/src/components/Fixtures/FixturesItem.tsx
Labels: bug

#189 Fix/email notifications
  client/src/components/Fixtures/FixturesItem.tsx
  server/schedulers/fixtures-reminder.sceduler.js
  server/schedulers/team-reminder.scheduler.js
Labels: bug

#207 Fix/league rank calculation
  client/src/containers/Leagues/LeagueDetails/index.tsx
  client/src/containers/Leagues/index.tsx
  server/api/services/league-participant.service.js
  server/api/services/league.service.js
  server/data/repositories/league-participant.repository.js
  server/helpers/calculate-league-rank.js
  server/socket/handlers.js
Labels: enhancement

#208 fix joining favourite club league more than once
  server/api/routes/profile.routes.js
Labels: bug

#211 implement notification center, fix email and app notifications
  client/src/components/Fixtures/FixturesItem.tsx
  client/src/components/PlayersSelection/action.type.ts
  client/src/components/PlayersSelection/actions.ts
  client/src/components/PlayersSelection/index.tsx
  client/src/containers/FixturesContainer/index.tsx
  client/src/containers/Players/index.tsx
  client/src/containers/Profile/actions.ts
  client/src/containers/Profile/components/EmailPreferences/index.tsx
  client/src/containers/Profile/components/NotificationCenter/index.tsx
  client/src/containers/Profile/components/Progress/index.tsx
  client/src/containers/Profile/index.tsx
  client/src/containers/Routing/index.tsx
  client/src/helpers/handlers.ts
  client/src/i18n/locales/en.json
  client/src/i18n/locales/ua.json
  client/src/services/profileService.ts
  client/src/types/user.type.ts
  server/api/services/player-match.service.js
  server/data/migrations/20190904093118-user.js
  server/data/models/user.js
  server/helpers/fixture-notification.helper.js
  server/schedulers/fixtures-reminder.sceduler.js
  server/schedulers/team-reminder.scheduler.js
  server/socket/handlers.js
Labels: bug, enhancement

#213 make spinner non-transculent, add close button to the player dialog
  client/src/components/PlayerDialog/index.tsx
  client/src/components/Spinner/styles.module.scss
Labels: bug

#216 Fix/simulate popup
  client/src/components/Dropdown/index.tsx
  client/src/containers/Live/components/SimulateModal.tsx
  client/test/specs/login/actions/loginForm.pa.js
Labels: bug

#217 change close button styles to achieve consistency
  client/src/components/PlayerDialog/index.tsx
Labels: bug

#218 fix set password inscription
  client/src/i18n/locales/en.json
  client/src/i18n/locales/ua.json
Labels: bug

#221 Fix/ui
  client/src/containers/Transfers/index.tsx
Labels: bug

#222 get rid of the date of the next fixture for each player on my team page
  client/src/components/Pitch/components/PitchPlayer/index.tsx
Labels: bug

#223 Fix/ui
  client/src/components/PlayerDialog/index.tsx
Labels: bug

#224 Fix/ui
  client/src/containers/Players/index.tsx
  client/src/i18n/locales/en.json
  client/src/i18n/locales/ua.json
Labels: bug

#226 Fix/ui
  client/src/components/AuthForms/LoginForm.tsx
  client/src/components/AuthForms/RegistrationForm.tsx
  client/src/containers/Leagues/CreateLeague/index.tsx
Labels: bug

#228 Fix/ui
  client/src/components/PlayerHighlight/index.tsx
  client/src/containers/Players/index.tsx
  client/src/types/player.types.ts
Labels: bug, enhancement

#232 Fix/ui
  client/src/components/ChangePasswordForms/ForgotPasswordForm.tsx
  client/src/components/ChangePasswordForms/ResetPasswordForm.tsx
  client/src/components/PlayerDialog/index.tsx
Labels: bug

#241 Fix/ui
  client/src/components/Leagues/LeagueTables/index.tsx
  client/src/containers/Players/index.tsx
  client/test/apiTests/data/profile.schema.js
  client/test/apiTests/leagues-services/data/leagues.payload.js
  client/test/apiTests/leagues-services/data/leagues.scenarios.json
  client/test/apiTests/leagues-services/data/leagues.schema.js
  client/test/apiTests/profile-services/data/profile.schema.js
Labels: bug
